In [19]:
import itertools

In [49]:
study_variants = ["full", "ablation"]
schemas = ["dwc", "eml"]
strategies = ["data-focus", "author-focus"]
configurations = [
    dict(
        provider="openai-platform",
        core_platform="openai", 
        proxy_platform="openai", 
        core_llm="gpt-5.4-mini", 
        embedding_model="text-embedding-3-small", 
        rag_llm="gpt-5.4-mini"
    ),
    dict(
        provider="surf",
        core_platform="surf-pilot", 
        proxy_platform="openai", 
        core_llm="gpt-oss-120b", 
        embedding_model="text-embedding-3-small", 
        rag_llm="gpt-5.4-mini"
    ),
    dict(
        provider="surf",
        core_platform="surf-pilot", 
        proxy_platform="openai", 
        core_llm="mistral-small-3.2", 
        embedding_model="text-embedding-3-small", 
        rag_llm="gpt-5.4-mini"
    ),
    dict(
        provider="ivi",
        core_platform="surf-ivi", 
        proxy_platform="openai", 
        core_llm="o3-mini", 
        embedding_model="text-embedding-3-small", 
        rag_llm="gpt-5.4-mini"
    ),
]

In [50]:
scenarios = list(itertools.product(study_variants, schemas, strategies, configurations))

In [51]:
scenarios

[('full',
  'dwc',
  'data-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'data-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'author-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'dwc',
  'author-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'data-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'data-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'author-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('full',
  'eml',
  'author-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'data-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'data-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'author-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'dwc',
  'author-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'data-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'data-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'data-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'author-focus',
  {'provider': 'openai-platform',
   'core_platform': 'openai',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-5.4-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'gpt-oss-120b',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'author-focus',
  {'provider': 'surf',
   'core_platform': 'surf-pilot',
   'proxy_platform': 'openai',
   'core_llm': 'mistral-small-3.2',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'}),
 ('ablation',
  'eml',
  'author-focus',
  {'provider': 'ivi',
   'core_platform': 'surf-ivi',
   'proxy_platform': 'openai',
   'core_llm': 'o3-mini',
   'embedding_model': 'text-embedding-3-small',
   'rag_llm': 'gpt-5.4-mini'})]

In [52]:
len(scenarios)

32

In [53]:
import pandas as pd

In [56]:
scenario_records = [
    {
        "variant": s[0],
        "schema": s[1],
        "strategy": s[2],
        "provider": s[3]["provider"],
        "config": s[3],
    } for s in scenarios
]

In [57]:
scenarios_df = pd.DataFrame.from_records(scenario_records)

In [58]:
scenarios_df.describe(include="all")

,variant,schema,strategy,provider,config
count,32,32,32,32,32
unique,2,2,2,3,4
top,full,dwc,data-focus,surf,"{'provider': 'openai-platform', 'core_platform..."
freq,16,16,16,16,8

In [59]:
scenarios_base_platform = scenarios_df[scenarios_df["config"].apply(lambda c: c["core_platform"] == "openai")]
scenarios_base_platform

,variant,schema,strategy,provider,config
0,full,dwc,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
4,full,dwc,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
8,full,eml,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
12,full,eml,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
16,ablation,dwc,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
20,ablation,dwc,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
24,ablation,eml,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
28,ablation,eml,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."

In [60]:
scenarios_base_platform_full = scenarios_base_platform[scenarios_base_platform["variant"]=="full"]
scenarios_base_platform_full

,variant,schema,strategy,provider,config
0,full,dwc,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
4,full,dwc,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
8,full,eml,data-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."
12,full,eml,author-focus,openai-platform,"{'provider': 'openai-platform', 'core_platform..."

In [61]:
scenarios_df.to_csv("experiment_scenarios.csv")