```latex
% 
\paragraph{Point-wise metadata assessment.} 
% 
We first derive and assess the individual characteristics of generated metadata instances:

\begin{enumerate}
    \item \emph{Structural Characteristics}: we derive the structural properties of the generated metadata instances as a synopses of their XML trees. We collect the tree sizes, depths, and node degrees.

    \item \emph{Syntactic Correctness}: we use the original XML Schema Definitions (XSD)s specified in the experiment set $\mathcal{S}$, to instantiate XML validators: $\mathcal{E}_{\dwctext}$ and $\mathcal{E}_{\eml}$. A validator receives a metadata instance, and returns a list of schema violations: $\mathcal{E}_{s\in\mathcal{S}}:\mathcal{M}\rightarrow[E_{s\in\mathcal{S}}]$.
    We apply it to metadata files created by \emph{massi} and store the pass or fail responses and all reported errors. We compute the correctness coefficient as: 
    \[
    corr(t_1,s) = 1 - \frac{\mid{\mathcal{E}_{s}(t_1)}\mid}{size(t_1)}
    \]
\end{enumerate}
```

# Point-Wise Generated Metadata  

- Compute the following sub-section goals, grouped by `schema` and `strategy`.

In [2]:
!cd ../../.. && pip install -v . --group=dev --group=observability --group=analysis

Using pip 25.3 from /opt/conda/lib/python3.13/site-packages/pip (python 3.13)
Processing /home/jovyan/work
  Running command installing build dependencies
  Using pip 25.3 from /opt/conda/lib/python3.13/site-packages/pip (python 3.13)
  Collecting setuptools>=40.8.0
    Obtaining dependency information for setuptools>=40.8.0 from https://files.pythonhosted.org/packages/9d/76/f789f7a86709c6b087c5a2f52f911838cad707cc613162401badc665acfe/setuptools-82.0.1-py3-none-any.whl.metadata
    Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
  Using cached setuptools-82.0.1-py3-none-any.whl (1.0 MB)
  Installing collected packages: setuptools
  Successfully installed setuptools-82.0.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  running egg_info
  writing massi.egg-info/PKG-INFO
  writing dependency_links to massi.egg-info/dependency_links.txt
  writing requirements to massi.egg-info/requires.txt
  writing top-level names to massi.egg-info/top_level.txt
  reading manifest file 'massi.egg-info/SOURCES.txt'
  writing manifest file 'massi.egg-info/SOURCES.txt'
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-9blcyn47/massi.egg-info
  writing /tmp/pip-modern-metadata-9blcyn47/massi.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-9blcyn47/massi.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-modern-metadata-9blcyn47/massi.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-9blcyn47/massi.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-9blcyn47/massi.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-9blcyn47/massi.egg-info/SOURCES.txt'
  writing manifest file '/tmp/pip-modern-metadata-9blcyn47/massi.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-9blcyn47/massi-0.1.0.dist-info'
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: black>=26.1.0 in /opt/conda/lib/python3.13/site-packages (26.3.1)
Requirement already satisfied: isort>=7.0.0 in /opt/conda/lib/python3.13/site-packages (8.0.1)
Requirement already satisfied: langgraph-cli>=0.4.11 in /opt/conda/lib/python3.13/site-packages (from langgraph-cli[inmem]>=0.4.11) (0.4.24)
Requirement already satisfied: mypy>=1.19.1 in /opt/conda/lib/python3.13/site-packages (1.20.2)
Requirement already satisfied: pytest>=9.0.2 in /opt/conda/lib/python3.13/site-packages (9.0.3)
Requirement already satisfied: pytest-timeout>=2.4.0 in /opt/conda/lib/python3.13/site-packages (2.4.0)
Requirement already satisfied: pytest-xdist>=3.8.0 in /opt/conda/lib/python3.13/site-packages (from pytest-xdist[psutil]>=3.8.0) (3.8.0)
Requirement already satisfied: tenacity>=9.1.4 in /opt/conda/lib/python3.13/site-packages (9.1.4)
Requirement already satisfied: xmldiff>=2.7.0 in /opt/conda/lib/python3.13/site-packages (2.7.0)
Requirement already satisfied: lmnr==0.7.47 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.7.47)
Requirement already satisfied: apted>=1.0.3 in /opt/conda/lib/python3.13/site-packages (1.0.3)
Requirement already satisfied: matplotlib>=3.10.9 in /opt/conda/lib/python3.13/site-packages (3.10.9)
Requirement already satisfied: duckdb>=1.5.1 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (1.5.2)
Requirement already satisfied: grandalf>=0.8 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (0.8)
Requirement already satisfied: ipython>=8.38.0 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (9.7.0)
Requirement already satisfied: ipywidgets>=8.1.8 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (8.1.8)
Requirement already satisfied: jsonschema>=4.25.1 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (4.25.1)
Requirement already satisfied: langchain>=1.2.0 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (1.2.17)
Requirement already satisfied: langchain-community>=0.4.1 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (0.4.1)
Requirement already satisfied: langchain-experimental>=0.4.1 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (0.4.1)
Requirement already satisfied: langchain-ollama>=1.0.1 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (1.1.0)
Requirement already satisfied: langchain-openai>=1.1.9 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (1.2.1)
Requirement already satisfied: langgraph>=1.0.5 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (1.1.10)
Requirement already satisfied: lxml>=6.1.0 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (6.1.0)
Requirement already satisfied: numpy>=2.4.4 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (2.4.4)
Requirement already satisfied: pandas>=3.0.0 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (3.0.2)
Requirement already satisfied: pymupdf>=1.27.2.3 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (1.27.2.3)
Requirement already satisfied: pypdf>=6.10.0 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (6.10.2)
Requirement already satisfied: python-dotenv>=1.2.1 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (1.2.2)
Requirement already satisfied: requests>=2.32.5 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (2.32.5)
Requirement already satisfied: tabulate>=0.10.0 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (0.10.0)
Requirement already satisfied: xmlschema>=4.3.1 in /opt/conda/lib/python3.13/site-packages (from massi==0.1.0) (4.3.1)
Requirement already satisfied: httpx<1.0.0,>=0.24.0 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (0.28.1)
Requirement already satisfied: lmnr-claude-code-proxy>=0.1.17 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (0.1.21)
Requirement already satisfied: opentelemetry-api<2.0.0,>=1.39.0 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (1.39.1)
Requirement already satisfied: opentelemetry-sdk<2.0.0,>=1.39.0 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (1.39.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-http<2.0.0,>=1.39.0 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (1.39.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc<2.0.0,>=1.39.0 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (1.39.1)
Requirement already satisfied: opentelemetry-instrumentation<1.0.0,>=0.54b0 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (0.60b1)
Requirement already satisfied: opentelemetry-instrumentation-threading<1.0.0,>=0.54b0 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (0.60b1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.60b1 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (0.60b1)
Requirement already satisfied: opentelemetry-semantic-conventions-ai==0.4.13 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (0.4.13)
Requirement already satisfied: orjson<4.0.0,>=3.0.0 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (3.11.8)
Requirement already satisfied: packaging>=22.0 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (25.0)
Requirement already satisfied: pydantic<3.0.0,>=2.0.3 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (2.12.4)
Requirement already satisfied: tqdm>=4.0 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (4.67.1)
Requirement already satisfied: grpcio>=1 in /opt/conda/lib/python3.13/site-packages (from lmnr==0.7.47->lmnr[all]==0.7.47) (1.78.0)
Requirement already satisfied: opentelemetry-instrumentation-alephalpha==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-bedrock==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-chromadb==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-cohere==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-crewai==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-haystack==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-lancedb==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-langchain==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-llamaindex==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-marqo==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-mcp==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-milvus==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-mistralai==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-ollama==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-pinecone==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-qdrant==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-replicate==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-sagemaker==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-together==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-transformers==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-vertexai==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-watsonx==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: opentelemetry-instrumentation-weaviate==0.52.4 in /opt/conda/lib/python3.13/site-packages (from lmnr[all]==0.7.47) (0.52.4)
Requirement already satisfied: anthropic>=0.17.0 in /opt/conda/lib/python3.13/site-packages (from opentelemetry-instrumentation-bedrock==0.52.4->lmnr[all]==0.7.47) (0.99.0)
Requirement already satisfied: tokenizers>=0.13.0 in /opt/conda/lib/python3.13/site-packages (from opentelemetry-instrumentation-bedrock==0.52.4->lmnr[all]==0.7.47) (0.23.1)
Requirement already satisfied: inflection<0.6.0,>=0.5.1 in /opt/conda/lib/python3.13/site-packages (from opentelemetry-instrumentation-llamaindex==0.52.4->lmnr[all]==0.7.47) (0.5.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /opt/conda/lib/python3.13/site-packages (from opentelemetry-semantic-conventions==0.60b1->lmnr==0.7.47->lmnr[all]==0.7.47) (4.15.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /opt/conda/lib/python3.13/site-packages (from opentelemetry-api<2.0.0,>=1.39.0->lmnr==0.7.47->lmnr[all]==0.7.47) (8.7.0)
Requirement already satisfied: anyio in /opt/conda/lib/python3.13/site-packages (from httpx<1.0.0,>=0.24.0->lmnr==0.7.47->lmnr[all]==0.7.47) (4.11.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.13/site-packages (from httpx<1.0.0,>=0.24.0->lmnr==0.7.47->lmnr[all]==0.7.47) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.13/site-packages (from httpx<1.0.0,>=0.24.0->lmnr==0.7.47->lmnr[all]==0.7.47) (1.0.9)
Requirement already satisfied: idna in /opt/conda/lib/python3.13/site-packages (from httpx<1.0.0,>=0.24.0->lmnr==0.7.47->lmnr[all]==0.7.47) (3.11)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.13/site-packages (from httpcore==1.*->httpx<1.0.0,>=0.24.0->lmnr==0.7.47->lmnr[all]==0.7.47) (0.16.0)
Requirement already satisfied: zipp>=3.20 in /opt/conda/lib/python3.13/site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api<2.0.0,>=1.39.0->lmnr==0.7.47->lmnr[all]==0.7.47) (3.23.0)
Requirement already satisfied: googleapis-common-protos~=1.57 in /opt/conda/lib/python3.13/site-packages (from opentelemetry-exporter-otlp-proto-grpc<2.0.0,>=1.39.0->lmnr==0.7.47->lmnr[all]==0.7.47) (1.74.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.39.1 in /opt/conda/lib/python3.13/site-packages (from opentelemetry-exporter-otlp-proto-grpc<2.0.0,>=1.39.0->lmnr==0.7.47->lmnr[all]==0.7.47) (1.39.1)
Requirement already satisfied: opentelemetry-proto==1.39.1 in /opt/conda/lib/python3.13/site-packages (from opentelemetry-exporter-otlp-proto-grpc<2.0.0,>=1.39.0->lmnr==0.7.47->lmnr[all]==0.7.47) (1.39.1)
Requirement already satisfied: protobuf<7.0,>=5.0 in /opt/conda/lib/python3.13/site-packages (from opentelemetry-proto==1.39.1->opentelemetry-exporter-otlp-proto-grpc<2.0.0,>=1.39.0->lmnr==0.7.47->lmnr[all]==0.7.47) (6.33.6)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in /opt/conda/lib/python3.13/site-packages (from opentelemetry-instrumentation<1.0.0,>=0.54b0->lmnr==0.7.47->lmnr[all]==0.7.47) (1.17.3)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.0.3->lmnr==0.7.47->lmnr[all]==0.7.47) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/conda/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.0.3->lmnr==0.7.47->lmnr[all]==0.7.47) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.0.3->lmnr==0.7.47->lmnr[all]==0.7.47) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.13/site-packages (from requests>=2.32.5->massi==0.1.0) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.13/site-packages (from requests>=2.32.5->massi==0.1.0) (2.5.0)
Requirement already satisfied: click>=8.0.0 in /opt/conda/lib/python3.13/site-packages (from black>=26.1.0) (8.3.0)
Requirement already satisfied: mypy-extensions>=0.4.3 in /opt/conda/lib/python3.13/site-packages (from black>=26.1.0) (1.1.0)
Requirement already satisfied: pathspec>=1.0.0 in /opt/conda/lib/python3.13/site-packages (from black>=26.1.0) (1.1.1)
Requirement already satisfied: platformdirs>=2 in /opt/conda/lib/python3.13/site-packages (from black>=26.1.0) (4.5.0)
Requirement already satisfied: pytokens~=0.4.0 in /opt/conda/lib/python3.13/site-packages (from black>=26.1.0) (0.4.1)
Requirement already satisfied: langgraph-sdk>=0.1.0 in /opt/conda/lib/python3.13/site-packages (from langgraph-cli>=0.4.11->langgraph-cli[inmem]>=0.4.11) (0.3.14)
Requirement already satisfied: librt>=0.8.0 in /opt/conda/lib/python3.13/site-packages (from mypy>=1.19.1) (0.10.0)
Requirement already satisfied: iniconfig>=1.0.1 in /opt/conda/lib/python3.13/site-packages (from pytest>=9.0.2) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /opt/conda/lib/python3.13/site-packages (from pytest>=9.0.2) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /opt/conda/lib/python3.13/site-packages (from pytest>=9.0.2) (2.19.2)
Requirement already satisfied: execnet>=2.1 in /opt/conda/lib/python3.13/site-packages (from pytest-xdist>=3.8.0->pytest-xdist[psutil]>=3.8.0) (2.1.2)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.13/site-packages (from xmldiff>=2.7.0) (80.9.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.13/site-packages (from matplotlib>=3.10.9) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.13/site-packages (from matplotlib>=3.10.9) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.13/site-packages (from matplotlib>=3.10.9) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.13/site-packages (from matplotlib>=3.10.9) (1.4.9)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.13/site-packages (from matplotlib>=3.10.9) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.13/site-packages (from matplotlib>=3.10.9) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.13/site-packages (from matplotlib>=3.10.9) (2.9.0.post0)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/conda/lib/python3.13/site-packages (from anthropic>=0.17.0->opentelemetry-instrumentation-bedrock==0.52.4->lmnr[all]==0.7.47) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /opt/conda/lib/python3.13/site-packages (from anthropic>=0.17.0->opentelemetry-instrumentation-bedrock==0.52.4->lmnr[all]==0.7.47) (0.18.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /opt/conda/lib/python3.13/site-packages (from anthropic>=0.17.0->opentelemetry-instrumentation-bedrock==0.52.4->lmnr[all]==0.7.47) (0.14.0)
Requirement already satisfied: sniffio in /opt/conda/lib/python3.13/site-packages (from anthropic>=0.17.0->opentelemetry-instrumentation-bedrock==0.52.4->lmnr[all]==0.7.47) (1.3.1)
Requirement already satisfied: decorator>=4.3.2 in /opt/conda/lib/python3.13/site-packages (from ipython>=8.38.0->massi==0.1.0) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /opt/conda/lib/python3.13/site-packages (from ipython>=8.38.0->massi==0.1.0) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in /opt/conda/lib/python3.13/site-packages (from ipython>=8.38.0->massi==0.1.0) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in /opt/conda/lib/python3.13/site-packages (from ipython>=8.38.0->massi==0.1.0) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.13/site-packages (from ipython>=8.38.0->massi==0.1.0) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/conda/lib/python3.13/site-packages (from ipython>=8.38.0->massi==0.1.0) (3.0.52)
Requirement already satisfied: stack_data>=0.6.0 in /opt/conda/lib/python3.13/site-packages (from ipython>=8.38.0->massi==0.1.0) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /opt/conda/lib/python3.13/site-packages (from ipython>=8.38.0->massi==0.1.0) (5.14.3)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.13/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=8.38.0->massi==0.1.0) (0.2.14)
Requirement already satisfied: comm>=0.1.3 in /opt/conda/lib/python3.13/site-packages (from ipywidgets>=8.1.8->massi==0.1.0) (0.2.3)

> **Collecting results and ground-truth cases**

In [4]:
import pandas as pd

In [7]:
gbif_cases = pd.read_csv("../../runtime/full_gbif_cases.csv")

In [8]:
experiment_results = pd.read_csv("../../runtime/experiment_cross_scenarios_cases.log.csv")

In [12]:
dwc_data_results = experiment_results[(experiment_results["schema"] == "dwc") & (experiment_results["strategy"] == "data-focus")]
dwc_author_results = experiment_results[(experiment_results["schema"] == "dwc") & (experiment_results["strategy"] == "author-focus")]

eml_data_results = experiment_results[(experiment_results["schema"] == "eml") & (experiment_results["strategy"] == "data-focus")]
eml_author_results = experiment_results[(experiment_results["schema"] == "eml") & (experiment_results["strategy"] == "author-focus")]

In [19]:
from IPython.display import display, display_markdown

> **Grouping by schema and strategy**

In [28]:
result_groups = {
    "dwc-x-data": dwc_data_results.sort_values(by="short_scenario_x_case_tag").copy().reset_index(),
    "dwc-x-author": dwc_author_results.sort_values(by="short_scenario_x_case_tag").copy().reset_index(), 
    "eml-x-data": eml_data_results.sort_values(by="short_scenario_x_case_tag").copy().reset_index(), 
    "eml-x-author": eml_author_results.sort_values(by="short_scenario_x_case_tag").copy().reset_index(),
}

for g, rs in result_groups.items():
    display(f"> --- Result Group: `{g}` ---")
    display(rs.describe())

'> --- Result Group: `dwc-x-data` ---'

,index,Unnamed: 0_x,scenario_id,Unnamed: 0_y,data_standard,case_id,duration_seconds,timestamp
count,179.000000,179.0,179.0,179.000000,179.0,179.000000,179.000000,1.790000e+02
mean,164.296089,0.0,0.0,153.513966,2.0,89.000000,46.359027,1.778160e+09
std,99.617169,0.0,0.0,99.156009,0.0,51.816986,77.392903,1.187505e+04
min,0.000000,0.0,0.0,0.000000,2.0,0.000000,12.870421,1.778149e+09
25%,84.500000,0.0,0.0,68.000000,2.0,44.500000,22.477583,1.778155e+09
50%,159.000000,0.0,0.0,151.000000,2.0,89.000000,30.010789,1.778159e+09
75%,263.500000,0.0,0.0,233.500000,2.0,133.500000,43.288641,1.778165e+09
max,444.000000,0.0,0.0,336.000000,2.0,178.000000,765.560462,1.778260e+09

'> --- Result Group: `dwc-x-author` ---'

,index,Unnamed: 0_x,scenario_id,Unnamed: 0_y,data_standard,case_id,duration_seconds,timestamp
count,179.000000,179.0,179.0,179.000000,179.0,179.000000,179.000000,1.790000e+02
mean,194.670391,4.0,4.0,153.513966,2.0,89.000000,42.249969,1.778161e+09
std,109.385350,0.0,0.0,99.156009,0.0,51.816986,54.813842,1.193789e+04
min,10.000000,4.0,4.0,0.000000,2.0,0.000000,14.248861,1.778150e+09
25%,114.500000,4.0,4.0,68.000000,2.0,44.500000,24.495313,1.778156e+09
50%,189.000000,4.0,4.0,151.000000,2.0,89.000000,29.604584,1.778160e+09
75%,310.500000,4.0,4.0,233.500000,2.0,133.500000,42.310426,1.778167e+09
max,445.000000,4.0,4.0,336.000000,2.0,178.000000,478.510206,1.778260e+09

'> --- Result Group: `eml-x-data` ---'

,index,Unnamed: 0_x,scenario_id,Unnamed: 0_y,data_standard,case_id,duration_seconds,timestamp
count,179.000000,179.0,179.0,179.000000,179.0,179.000000,179.000000,1.790000e+02
mean,515.670391,8.0,8.0,153.513966,2.0,89.000000,445.775805,1.778304e+09
std,97.111935,0.0,0.0,99.156009,0.0,51.816986,394.417847,3.889963e+04
min,354.000000,8.0,8.0,0.000000,2.0,0.000000,38.520714,1.778230e+09
25%,439.500000,8.0,8.0,68.000000,2.0,44.500000,312.525535,1.778249e+09
50%,527.000000,8.0,8.0,151.000000,2.0,89.000000,407.317098,1.778325e+09
75%,611.500000,8.0,8.0,233.500000,2.0,133.500000,496.024076,1.778331e+09
max,702.000000,8.0,8.0,336.000000,2.0,178.000000,4997.299114,1.778334e+09

'> --- Result Group: `eml-x-author` ---'

,index,Unnamed: 0_x,scenario_id,Unnamed: 0_y,data_standard,case_id,duration_seconds,timestamp
count,179.000000,179.0,179.0,179.000000,179.0,179.000000,179.000000,1.790000e+02
mean,555.363128,12.0,12.0,153.513966,2.0,89.000000,261.103811,1.778308e+09
std,108.616256,0.0,0.0,99.156009,0.0,51.816986,67.038688,3.772579e+04
min,356.000000,12.0,12.0,0.000000,2.0,0.000000,51.728838,1.778231e+09
25%,480.500000,12.0,12.0,68.000000,2.0,44.500000,221.043937,1.778322e+09
50%,567.000000,12.0,12.0,151.000000,2.0,89.000000,264.250012,1.778327e+09
75%,666.500000,12.0,12.0,233.500000,2.0,133.500000,305.515517,1.778333e+09
max,715.000000,12.0,12.0,336.000000,2.0,178.000000,466.105851,1.778335e+09

> **Some useful utilities**

In [34]:
from pathlib import Path

In [35]:
EXPERIMENT_BASE_DIR = "../../../_data/gbif_data_archive/"

def grounded_path(suffix: str | Path) -> Path:
    return Path(EXPERIMENT_BASE_DIR) / suffix

> **Now we are ready to proceed with the evaluations**

In [32]:
# see next cells

## Structural Characteristics

- XML tree size
- XML tree depths
- XML tree node degrees

## Syntactic Correctness

- XML validity given the XSD schema validator